### GET /podcasts
GET http://localhost:8082/podcasts
Accept: application/json


### GET /podcasts?ids
GET http://localhost:8082/podcasts?ids=PC1,PC2,PC3
Accept: application/json


### GET /podcasts/{id}
GET http://localhost:8082/podcasts/PC1
Accept: application/json